In [1]:
import torch

1. 随机数

In [2]:
x = torch.randn( 4, 5 )
y = torch.randn( 4, 5 )
z = torch.randn( 4, 5 )
x, y, z

(tensor([[-0.9943, -0.6065, -0.5218, -0.1695,  0.4143],
         [-0.3911, -0.3146,  2.1595, -0.4808,  0.5162],
         [-0.5482,  0.8760, -2.2544, -0.7170,  0.7545],
         [-0.8475,  1.1356,  0.9290,  0.3876,  2.4676]]),
 tensor([[ 0.7361,  0.4775, -1.2555, -0.4689, -1.1327],
         [-0.2100,  0.9687,  1.5240,  0.6131,  0.2964],
         [-0.0666, -0.2799,  1.4633,  3.1023, -1.1122],
         [ 0.8412,  1.2276, -0.2365,  0.1413, -0.0675]]),
 tensor([[-9.0051e-01, -7.7932e-01,  1.0446e-03,  2.1479e-01,  1.0633e+00],
         [-1.2076e+00,  2.6069e-01,  1.8750e+00, -3.6173e-02,  6.9895e-02],
         [-1.1194e+00, -3.5104e-01, -1.3703e+00, -1.8741e-01, -6.6004e-01],
         [-2.0014e+00, -1.8715e+00, -3.2859e-01, -4.2645e-01, -1.8414e-01]]))

2. torch.max
    1) 输出tensor中的最大元素
    2) 在某个dim上找最大值
    3) 比较两个tensor

In [3]:
m = torch.max( x )
m

tensor(2.4676)

In [4]:
m, idx = torch.max( x, 0 )      # m, idx = torch.max( imput = x, dim = 0 )
print( m )                      # 依次是每一列中的最大值
print( idx )                    # 每一列中最大值的竖直方向的顺序

tensor([-0.3911,  1.1356,  2.1595,  0.3876,  2.4676])
tensor([1, 3, 1, 3, 3])


In [5]:
mt = torch.max( x, y )
mt

tensor([[ 0.7361,  0.4775, -0.5218, -0.1695,  0.4143],
        [-0.2100,  0.9687,  2.1595,  0.6131,  0.5162],
        [-0.0666,  0.8760,  1.4633,  3.1023,  0.7545],
        [ 0.8412,  1.2276,  0.9290,  0.3876,  2.4676]])

应用

In [6]:
import torch.utils.data

class EgDataset(torch.utils.data.Dataset):
    def __init__(self):
        self.data = 'abcdefghijklmnop'
    def __getitem__(self, index):
        return self.data[index]
    def __len__(self):
        return len(self.data)


dataset = EgDataset()           # 实例化
# dataloader = torch.utils.data.DataLoader( dataset, batch_size = 1, shuffle = True, num_workers = 0 )
# dataloader = torch.utils.data.DataLoader( dataset, batch_size = 1, shuffle = False, num_workers = 0 )
dataloader = torch.utils.data.DataLoader( dataset, batch_size = 4, shuffle = False, num_workers = 0 )
for d in dataloader:
    print( d, end=' ' )

['a', 'b', 'c', 'd'] ['e', 'f', 'g', 'h'] ['i', 'j', 'k', 'l'] ['m', 'n', 'o', 'p'] 

In [7]:
mt = torch.cat( [x, y ,z ], dim = 1 )
mt

tensor([[-9.9434e-01, -6.0645e-01, -5.2180e-01, -1.6953e-01,  4.1426e-01,
          7.3613e-01,  4.7752e-01, -1.2555e+00, -4.6891e-01, -1.1327e+00,
         -9.0051e-01, -7.7932e-01,  1.0446e-03,  2.1479e-01,  1.0633e+00],
        [-3.9114e-01, -3.1458e-01,  2.1595e+00, -4.8075e-01,  5.1620e-01,
         -2.1004e-01,  9.6868e-01,  1.5240e+00,  6.1310e-01,  2.9644e-01,
         -1.2076e+00,  2.6069e-01,  1.8750e+00, -3.6173e-02,  6.9895e-02],
        [-5.4823e-01,  8.7601e-01, -2.2544e+00, -7.1703e-01,  7.5453e-01,
         -6.6635e-02, -2.7988e-01,  1.4633e+00,  3.1023e+00, -1.1122e+00,
         -1.1194e+00, -3.5104e-01, -1.3703e+00, -1.8741e-01, -6.6004e-01],
        [-8.4750e-01,  1.1356e+00,  9.2897e-01,  3.8762e-01,  2.4676e+00,
          8.4124e-01,  1.2276e+00, -2.3645e-01,  1.4127e-01, -6.7537e-02,
         -2.0014e+00, -1.8715e+00, -3.2859e-01, -4.2645e-01, -1.8414e-01]])

矩阵乘法

In [8]:
a = torch.tensor( [[1, -1],
                  [2, 3]] )
k1 = a @ a.T
k2 = a.matmul( a.T )
k1, k2

(tensor([[ 2, -1],
         [-1, 13]]),
 tensor([[ 2, -1],
         [-1, 13]]))

对应元素相乘

In [9]:
k3 = a * a
k4 = a.mul( a )
k3, k4

(tensor([[1, 1],
         [4, 9]]),
 tensor([[1, 1],
         [4, 9]]))

.sum & .item()

In [10]:
s = a.sum()
s_item = s.item()
s, s_item

(tensor(5), 5)

Dataloader:避免过拟合每个epoch都通过dataloader进行reshuffle

In [11]:
trainloader = torch.utils.data.DataLoader( dataset, batch_size = 4, shuffle =True, num_workers = 0 )

自定义模型

In [12]:
import torch.nn as nn
class MyModel( nn.Module ):
    def __init__( self ):
        super( MyModel, self ).__init__()
        self.flatten = nn.Flatten()
        self.OutPut = nn.Sequential(                    # 有序容器
            nn.Linear( 32 * 32, 512 ),
            nn.ReLU(),
            nn.Linear( 512, 10 ),
            nn.ReLU(),
            nn.Linear( 10, 2 )
        )
    def forward(self, x):
        x = self.flatten( x )
        return self.OutPut( x )

测试

In [13]:
x = torch.randn( 1, 32, 32 )
method = MyModel()
predict = nn.Softmax( dim = 1 )( method( x ) )
predict_y = predict.argmax( dim = 1 )
predict, predict_y

(tensor([[0.4188, 0.5812]], grad_fn=<SoftmaxBackward0>), tensor([1]))

In [14]:
img = torch.randn( 3, 32, 32 )
img.size()

torch.Size([3, 32, 32])

In [15]:
flatten = nn.Flatten()
f_img = flatten( img )
f_img.size()                # 32*32 = 1024

torch.Size([3, 1024])

In [16]:
layer1 = nn.Linear( 32*32, 256 )
h1 = layer1( f_img )
h1.size()

torch.Size([3, 256])

In [17]:
h2 = nn.ReLU()( h1 )
h2.size()

torch.Size([3, 256])

In [18]:
layer2 = nn.Linear( 256, 10 )
h3 = layer2( h2 )
h3.size()

torch.Size([3, 10])

In [19]:
sm = nn.Softmax( dim = 1 )( h3 )
sm

tensor([[0.1208, 0.0840, 0.0840, 0.0753, 0.1087, 0.0679, 0.0750, 0.1561, 0.1129,
         0.1152],
        [0.1248, 0.1183, 0.0806, 0.1278, 0.0810, 0.0517, 0.1007, 0.1238, 0.0867,
         0.1047],
        [0.1111, 0.1036, 0.0933, 0.0941, 0.0865, 0.0719, 0.0905, 0.1269, 0.1443,
         0.0778]], grad_fn=<SoftmaxBackward0>)

微分

In [20]:
x = torch.ones( 5 )         # inputs
y = torch.zeros( 5 )         # expects
w = torch.randn( 5, 5, requires_grad=True )
bias = torch.randn( 5, requires_grad=True )
z = torch.matmul( x, w ) + bias

w, bias, z

(tensor([[-0.0521,  0.6396,  0.0494,  0.2951, -1.2098],
         [ 2.7282, -0.7458, -0.7573, -2.4858,  1.1581],
         [-1.0032, -1.2807, -0.8904, -0.4516,  1.1434],
         [-0.2337,  1.7488, -0.9077, -0.0215,  0.7101],
         [ 0.3119, -0.8306,  2.4479, -1.7070, -0.5684]], requires_grad=True),
 tensor([-0.0536, -0.6724, -1.0878, -0.0683,  0.8596], requires_grad=True),
 tensor([ 1.6976, -1.1410, -1.1460, -4.4391,  2.0930], grad_fn=<AddBackward0>))

In [21]:
# loss = nn.CrossEntropyLoss()( z, y )
loss_f = nn.MSELoss()
loss = loss_f( z, y )

loss.item()

5.916619777679443

In [25]:
t = torch.tensor( [[[1,2,3],
                   [4,5,6]],
                  [[7,8,9],
                  [10, 11, 12]]])
t.size()

torch.Size([2, 2, 3])

In [29]:
t = torch.flatten( t, 1 )
t, t.size()

(tensor([[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12]]),
 torch.Size([2, 6]))